name: Docker

on:
  push:
    tags: ["*.*.*"]

env:
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Retrieve tag name
        id: tag
        run: echo ::set-output name=version_tag::${GITHUB_REF/refs\/tags\//}

      - name: Retrieve Code
        run: |
          mkdir superset
          cd superset
          wget https://github.com/apache/superset/archive/refs/tags/${{ steps.tag.outputs.version_tag }}.tar.gz
          tar --strip-components=1 -xf ${{ steps.tag.outputs.version_tag }}.tar.gz

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: superset
          target: lean
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          push: true
          labels: ${{ steps.meta.outputs.labels }}
